---
- hosts: all
  user: localuser
  become: yes
  collections:
     - community.general
  tasks:

     - ansible.builtin.include_role:
         name: upgrade-rhel
       tags:
         - "upgrade_role"
